[book]
title = "Rust 程序设计语言 简体中文版"
authors = ["Steve Klabnik 和 Carol Nichols，以及来自 Rust 社区的贡献（Rust 中文社区翻译）"]
description = "Rust 程序设计语言 简体中文版"
language = "zh-CN"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/rustnotes/trpl-zh-cn/tree/main"
edit-url-template = "https://github.com/rustnotes/trpl-zh-cn/edit/main/{path}"

[output.typst-pdf]
pdf = true
section-number = true
